local CharacterAnimations = {}

CharacterAnimations.Hold = { id = "rbxassetid://96891909262325", props = {
	Looped = true,
}, methodsToCallOnLoad = {} }

CharacterAnimations.Throw = {
	id = "rbxassetid://93473524732787",
	props = {},
	methodsToCallOnLoad = {},
}

CharacterAnimations.Stack = {
	id = "rbxassetid://107590752344253",
	props = {},
	methodsToCallOnLoad = {},
}

CharacterAnimations.Swing = {
	id = "rbxassetid://114306001356252",
	props = {},
	methodsToCallOnLoad = {},
}

return CharacterAnimations
