local UpgradesConfig = {}

UpgradesConfig.AutoMoney = {
	ProductId = 1911281240,
	Title = "Auto Money",
	SubTitle = "Collect money automatically",
}

UpgradesConfig.AutoLoot = {
	ProductId = 1912376961,
	Title = "Auto Loot",
	SubTitle = "Collect ore automatically",
}

UpgradesConfig.DoubleOre = {
	ProductId = 1914074596,
	Title = "Double Ore",
	SubTitle = "Twice as many ores dropped",
}

return UpgradesConfig
