return {
	DataTemplate = {
		Cash = 1000,

		Index = {},
		Inventory = {},

		CashToClaim = 0,
		ProcessIncrement = 1,
		UnprocessedResources = 0,
		Resources = 0,

		ProcessUpgradeLevel = 1,
		Purchases = 0,

		ExtraStands = 0,
		TakenSlots = {},

		CashMultiplier = 1,
		CashMultiplierIndex = 1,

		AutoMoney = false,
		AutoLoot = false,
		DoubleOre = false,

		LastSeen = 0,
		JoinedBefore = false,

		PurchaseHistory = {},
	},
}
